### ISSUE TITLE
AttributeError: Can't pickle local object 'simulate.<locals>.pipe_call'

### ISSUE THREAD

**Issue by rbelew** [ICB-DCM/tumor2d#3]
trying the test invocation fails:

```
$ python
Python 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tumor2d
>>> simulate()
>>> tumor2d.simulate()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Volumes/Data/rikData/virtualenv/pyABC/tumor2d-master/tumor2d/simulate.py", line 70, in simulate
    proc.start()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'simulate.<locals>.pipe_call'
```

**Comment by yannikschaelte** [comment]
I am not the package owner, but I suspect this may be due to the default pickling behavior on mac having changed with python 3.8 (from fork to spawn). Running `multiprocessing.set_start_method("fork")` once per session at the beginning may help, see also https://github.com/pytest-dev/pytest-flask/issues/104
